### ISSUE TITLE
How to clean up various stacks of old code lying around

### ISSUE THREAD

**Issue by bas-rustenburg** [choderalab/bayesian-itc#12]
There are a bunch of directories like:
* `src`
* `python/attic`
* `python/examples`

We should figure out what to do with these snippets of outdated code.

**Comment by pgrinaway** [comment]
Is any of that code still useful, or has its functionality been duplicated elsewhere? If it's the latter, you can just delete it. For the bits that haven't been duplicated, maybe evaluate whether you want to fix/reimplement or discard.

IMHO having lots of unused code in a repo can be confusing...

**Comment by daveminh** [comment]
Congrats on finishing the refactoring! I agree that lots of unused code is confusing. If it is needed again, you can find it on github, right?

**Comment by bas-rustenburg** [comment]
It should be in the history yes. Deletion would not be unreasonable. Probably would be good to make a run through the code and perhaps open issues to re-implement any lost functionality.

In case we want to keep it, a suggestion:
Rename `src` to `attic`, and combine all the other unused scripts from the `python` directory so it does not get confused with the new/improved  scripts.

**Comment by jchodera** [comment]
At this point, I'd suggest creating separate PRs to prune various directories of unused code, one per directory (or group of logically related directories)..  We can discuss whether we need to retain anything from that folder in the PR.

**Comment by bas-rustenburg** [comment]
As discussed with John today, we did a large restructuring in #23 and got rid of old code.
