### ISSUE TITLE
Add Python 3 compatibility

### ISSUE THREAD

**Issue by jchodera** [choderalab/bayesian-itc#2]

**Comment by bas-rustenburg** [comment]
pymc3 is still in alpha. Can't guarantee that it is reliable.

**Comment by kyleabeauchamp** [comment]
Not related

**Comment by bas-rustenburg** [comment]
Does that mean pymc2 works for python 3?

**Comment by bas-rustenburg** [comment]
Ah, seems like it. I misinterpreted the naming. In that case, this is doable. Not an immediate priority though.

**Comment by kyleabeauchamp** [comment]
Yeah.

**Comment by jchodera** [comment]
Does it?  There are no python 3.x packages on the anaconda binstar channel:
https://binstar.org/anaconda/pymc/files

At the very least, we'll probably have to include recipes for `pymc` in the `omnia` conda channel and have Jenkins build versions ourself.

**Comment by bas-rustenburg** [comment]
I tested it, but I might have installed it from another binstar channel. Pymc has their own channel it seems.

**Comment by jchodera** [comment]
Some of those versions require very specific compilers to be installed, and
others require crazy compiler paths. We may still have to roll our own for
portability.

**Comment by bas-rustenburg** [comment]
Looks like I actually get it from the main channels: 

(py3k)~ ❯❯❯  conda search --override-channels --channel defaults pymc
Fetching package metadata: ..
pymc                         2.2                 np17py27_p0  defaults        
                             2.2                  np17py27_0  defaults        
                             2.3                  np17py27_0  defaults        
                             2.3                  np18py27_1  defaults        
                             2.3.2                np18py27_0  defaults        
                             2.3.2                np18py26_0  defaults        
                          .  2.3.3                np19py27_0  defaults        
                             2.3.3                np19py26_0  defaults        
                             2.3.3                np18py27_0  defaults        
                             2.3.3                np18py26_0  defaults        
                             2.3.4               np19py34_p0  defaults        [mkl]
                             2.3.4                np19py34_0  defaults        
                             2.3.4               np19py33_p0  defaults        [mkl]
                          .  2.3.4                np19py33_0  defaults        
                             2.3.4               np19py27_p0  defaults        [mkl]
                          .  2.3.4                np19py27_0  defaults        
                             2.3.4               np19py26_p0  defaults        [mkl]
                             2.3.4                np19py26_0  defaults

**Comment by bas-rustenburg** [comment]
See also:
http://repo.continuum.io/pkgs/

**Comment by jchodera** [comment]
Huh.  Does `conda` check there before checking binstar?

**Comment by bas-rustenburg** [comment]
I did not use the pymc channel, I use the main repo's. Also, resolved. We now have python 3 supported (as far as my machine goes it works.) Will test all the relevant :snake:'s on travis once I set up some basic testing.

**Comment by jchodera** [comment]
Is that a unicode Python?

**Comment by bas-rustenburg** [comment]
Yes.
